[package]
name = "domain"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.72"
futures-util = "0.3.28"
rust_decimal = "1.32"
anyhow = "1.0.75"
