[package]
name = "traits"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
models = { path = "../models" }
async-trait = "0.1.72"
rust_decimal = "1.32"
thiserror = "1.0"
